### ISSUE TITLE
Create and use a druid-pairtree extension

### ISSUE THREAD

**Issue by mjgiarlo** [sul-dlss/ocfl-rb#13]
Blocked by #12 

Once [storage root support](#12) is added, consider creating and adding support for using [community extensions](https://ocfl.github.io/extensions/) such as the druid-based pairtree directory layout we currently use in stacks, and want to keep supporting in the OCFL structure. The extension should be used by the gem to navigate from the storage root to an object root using our druid-based pairtree hierarchy. For inspiration, review other production OCFL libraries, e.g.:

* https://github.com/OCFL/ocfl-java/blob/main/docs/USAGE.md#ocfl-repository-configuration
* https://github.com/inveniosoftware/ocflcore#quick-start

**Comment by mjgiarlo** [comment]
@jcoyne should #12 also move to ready? Or do you not see this issue as blocked by 12? I figured the druidtree extension wasn't very useful without a storage root impl to build the tree out from.

**Comment by aaron-collier** [comment]
Is this: https://github.com/sul-dlss/ocfl-rb/blob/main/lib/ocfl/layouts/druid_tree.rb ?

Or is this something more about extracting the above into an "extension"?

**Comment by mjgiarlo** [comment]
@aaron-collier The latter, and then potentially changing the storage root API to opt into one or more extensions. It would be good to decide the extent to which we want ocfl-rb be extensible vs. hard-coded for our (Stanford's) needs, and I'm fine with whatever y'all come up with!

**Comment by mjgiarlo** [comment]
Here's an in-progress storage root extension: https://github.com/OCFL/extensions/pull/76

**Comment by mjgiarlo** [comment]
This tweaks the gem to "use" the in-progress OCFL extension for druid-trees: https://github.com/sul-dlss/ocfl-rb/pull/45
